### ISSUE TITLE
Could we setup a template defining the endpoint for our server?

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/product-de-bring-your-own-datacenter#10]
Onboarding clients would be easier if we could setup the endpoint ourselves. What do you recommend?

**Comment by fiskaltrust-ckr** [comment]
If i get your question right, this would be templating (can be found in our docs: https://docs.fiskaltrust.cloud/doc/productdescription-de-doc/for-posdealers/02-pre-sales/automatisierter-rollout.html)
