### ISSUE TITLE
Load Balancer Request Routing

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#11]
Is there a requirement that requests for a distinct cashbox always get routed to the same container in the Middleware cluster and if this requirement is in place, how will the cluster repair itself if a node in the cluster is taken down?

**Comment by fiskaltrust-ckr** [comment]
Given a BackendPOD runs a new Cashbox which is already running on an other BackendPOD then the existing Cashbox will dispose itself. This info is distributed via Redis-Publisher-Subscriber between the BackendPODs.
It is recommended to route to the same POD on CashboxID if possible to get optimal performance.
If a node in the cluster goes down the others should take the load until the orchestrator spins up another node.
The important thing to consider at this point is the time a new Cashbox needs on the first request for loading the configuration from helipad.
