### ISSUE TITLE
Cashbox Configuration Changes

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#12]
When I change the mysql ConnectionString configuration value for a queue on the portal sandbox, the change is not updated to the Middleware containers until they are restarted.
Does a Middleware container get the configurations for a cashbox from helipad on the first request only for that cashbox?

**Comment by fiskaltrust-ckr** [comment]
Given you change the configuration at the ft-portal and "rebuild the Cashbox", then the cashbox gets the configuration after restarting the Cashbox because the Cashbox only loads its config on startup. (So the Answer is "yes")

**Comment by Solrosy** [comment]
Thanks for this. It would be good if the cashbox would notice the config change and restart or update herself. How do we know?
How would we trigger this restart?

**Comment by Solrosy** [comment]
What kind of message is that exactly? Do you have sample code please?
Just add it to the documentation. :-)

**Comment by Solrosy** [comment]
Is there a way btw to update all POS operators with the latest package automatically or do we have to go into the Portal on each?

**Comment by fiskaltrust-ckr** [comment]
https://github.com/fiskaltrust/productdescription-de-doc/blob/master/for-posdealers/04-after-sales/how-to-mass-update-configuration.md
Does this answer your question?

**Comment by fiskaltrust-ckr** [comment]
https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/blob/master/OperationsReference.md
added :-)

**Comment by darek-phorest** [comment]
hi guys, in terms of mass update of the cashboxes on the eks cluster, how do we do that?
so let's say we did the mass update on the portal (https://github.com/fiskaltrust/productdescription-de-doc/blob/master/for-posdealers/04-after-sales/how-to-mass-update-configuration.md) and we want to role that out, do we restart the whole cluster? or is there a better way to do it ?

**Comment by fiskaltrust-ckr** [comment]
Hi Darek, thanks for this great question.
It depends on how much cashboxes you would like to update. Of course restarting all PODs is an option to update all cashboxes immediately. If you would like to update only a bunch of cashboxes, it would be possible to call the echo endpoint for every cashbox. 
Like what's the best option for your scenario.
I added a section to "Operations Reference" regarding this topic.
