### ISSUE TITLE
Application logs to file

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#13]
Can fiskaltrust.Middleware be configured to send application logs to a file on the local filesystem rather than stdout/stderr?

**Comment by fiskaltrust-ckr** [comment]
No, this is not intended. Usual logging practice in K8S environments is to handle logs via stdout/stderr.
https://kubernetes.io/docs/concepts/cluster-administration/logging/#cluster-level-logging-architectures
