### ISSUE TITLE
Hostname wildcard issue

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#14]
Currently seeing this 
`2020/10/19 12:39:32 kubernetes:secret|bring-your-own-datacenter|*|hostname=*: ERROR: WORKER PANICKED: unable to parse requirement: invalid label value: "*": at key: "hostname": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

message every 3 seconds in the logs. However, It doesn't appear to be affecting the operation of the load balancer.

It seems to be due to this issue:
https://github.com/datawire/ambassador/issues/2284
Can you give a workaround for your charts or support the workaround for this issue specified in the link in your charts?

**Comment by fiskaltrust-ckr** [comment]
Thank you for reporting this issue. We are working on that and provide updates to this issue.

**Comment by volllly** [comment]
You can add the `hostname` in the `config.yaml` like this
```yaml
ambassador: 
  config: 
    hostname: localhost
```
with the domain under which your ByoDC is reachable.

You can find a full list of supported config options [here](https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/blob/master/ParameterReference.md).
