### ISSUE TITLE
Redis Pod Replicas

### ISSUE THREAD

**Issue by seancarr26** [fiskaltrust/product-de-bring-your-own-datacenter#16]
In the helm chart value overrides, it is not possible to specify more than 1 pod replica for the redis container.
Is this by design or is it possible to have more than one pod replica for the redis container in the byodc cluster?

**Comment by fiskaltrust-ckr** [comment]
Hi Sean, thank you for that great question. The Redis-POD is per default a single instance to keep our chart simple.
If you prefer to operate Redis in a cluster feel free to use our charts as a blueprint and enhance it to your needs.
Of course, it is also possible to use your own Redis Instance or a PaaS Option if you operate on a public cloud.
