### ISSUE TITLE
byodc database per cashbox

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#21]
Hi there

it does seam like the byodc generates a database per cashbox. Is there any way we can know which database correlates to which cashbox ?

<img width="319" alt="Screenshot 2020-10-29 at 13 07 59" src="https://user-images.githubusercontent.com/34276999/97578486-25fbbe00-19f1-11eb-81d8-ae16aebd6378.png">

**Comment by fiskaltrust-ckr** [comment]
Hi Darek,
thank you for this question.
The Name is equal to the QueueID without hyphens (GUID).
BR
Christian
