### ISSUE TITLE
Failed to export TAR file from SCU

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#23]
Hi there, could we get some more info on the bellow error reported by byodc. We have disabled the tar file export in the portal for the tse

<img width="887" alt="Screenshot 2020-11-03 at 11 18 12" src="https://user-images.githubusercontent.com/34276999/97975587-a5aad380-1dc9-11eb-8350-d528533966f4.png">

What is the export used for by the way? Is it done on every receipt request ?

```
fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory[0]
      Worker created. cashboxid: e5db2934-bbcc-4f69-8d75-de51c5f7f8a1
fail: fiskaltrust.Middleware.Localization.QueueDE.SignProcessorDE[0]
      Failed to export TAR file from SCU.
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Convert.FromBase64String(String s)
   at fiskaltrust.Middleware.Localization.QueueDE.SignProcessorDE.ProcessTarFileExportAsync(Guid queueId, String cashboxIdentification, IDESSCD client, Boolean erase)
   at fiskaltrust.Middleware.Localization.QueueDE.SignProcessorDE.PerformTarFileExportAsync(ftQueueItem queueItem, ftQueue queue, ftQueueDE queueDE, IDESSCD client, Boolean erase)
```

**Comment by fiskaltrust-ckr** [comment]
Hi Darek,
thank you for asking this question.
As we mentioned earlier, this is a bug at fiskaly and we are looking forward that this will be fixed soon.
Regarding this question: TAR File Export on SCU gets triggered after every daily/monthly/yearly closing receipt

**Comment by darek-phorest** [comment]
any updates on this issue @fiskaltrust-ckr ?

**Comment by fiskaltrust-ckr** [comment]
@darek-phorest: unfortunately there is no info from fiskaly until now.
BR
Christian

**Comment by Solrosy** [comment]
Hi Christian, happy new year! Any news on this one please?
