### ISSUE TITLE
Kubernaut.io i/o timeout

### ISSUE THREAD

**Issue by adifan** [fiskaltrust/product-de-bring-your-own-datacenter#24]
getting a error in ambassador pod:

`020-11-05T08:58:15.581088766Z time="2020-11-05 08:58:15" level=error msg="telemetry: Post \"https://kubernaut.io/scout\": dial tcp 35.193.8.157:443: i/o timeout" func=github.com/datawire/apro/cmd/amb-sidecar/kale.telemetry file="github.com/datawire/apro/cmd/amb-sidecar/kale/kale.go:149" MAIN=kale_worker`

kubernaut.io is reachable in the pod when i use our proxy in the curl from the ambassador pod

`curl -v https://kubernaut.io/scout -x {internal_proxy}`
`< HTTP/1.1 200 Connection established`

How can i set proxy values?

**Comment by fiskaltrust-ckr** [comment]
Hi, may you post your config.yaml, or did you install our chart with default values?
Thank you in advance

**Comment by adifan** [comment]
`ambassador: 
  config: 
    hostname: localhost
byodc:
  env:
    http_proxy: http://atu-dsi-proxy:3128
    https_proxy: http://atu-dsi-proxy:3128
    no_proxy: .dsp.atu.de,.kube,.svc,.infrastructure,developer.atu.de,lab.it-solutions.atos.net,localhost`

**Comment by volllly** [comment]
Hi, [this guide](https://medium.com/@gargankur74/setting-up-standalone-kubernetes-cluster-behind-corporate-proxy-on-ubuntu-16-04-1f2aaa5a848) should help you set up kubernetes behind a proxy.

AFAIK ambassador provides no mechanism to do do this.
