### ISSUE TITLE
Production Set Up

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#25]
Hi there

We will be configuring our production infrastructure to support around 700 cashboxes. 

- Can you guys let us know how many nodes and the size of those nodes we will need to support that. 
- We are also interested in the size of the database that we will need this especially the number of connection that we will need to allow. Does each request to cashbox generate a new db connection, there is no connection pool from byodc pods to the db instance ? 
- we believe that redis instance can be kept to minimum as that is used only for synchronization

Thanks

**Comment by fiskaltrust-ckr** [comment]
Hi Darek,
thank you for your inquiry.
We have a theoretical sizing which is not production approved for now (keep that in mind pls):
For 700 cashboxes (queues) and 200 Receipts/day
- 3 BackendPODs (a 4vCPUs, 16GB RAM each)
- DB Storage estimated for 3 years on max receipts 1,5TB
But you may scale up/down on your application and POS behavior needs.
Redis is intended to be a small POD (as you said it is only for synchronizing)
I asked our engineering team regarding DB Connection pool and provide the answer in a later post
BR
Christian

**Comment by darek-phorest** [comment]
Hi Christian,

Thanks for Info. I hope you mean 200 receipts/day per cashbox so that would be 140 000 (700 * 200) across 3 BackendPods ?

Regards
Darek

**Comment by fiskaltrust-ckr** [comment]
Indeed, thanks for mentioning.
BTW, every queue starts its own database connection. It is meant to separate all queues so that they are independent of which POD they are running on...

**Comment by darek-phorest** [comment]
HI Christian

when you mentioned `3 BackendPODs (a 4vCPUs, 16GB RAM each)` i think you referred to 3 cluster nodes. Do you know how many byodc pods we should be running in the cluster with what cpu, memory limits, the default values for the pods from what i can see have the following setup:

limits:
      cpu: 100m
      memory: 100Mi

Thanks

**Comment by fiskaltrust-ckr** [comment]
Hi Darek,
thank you for this important question.
Of course, the default values are different to a production scale. It is up to you how much you scale your backendpods up and/or out). Our calculations are based on our previous production systems which are running on VM basis. As we mentioned at the beginning this product is new. Feel free to create synthetic tests, I appreciate your feedback!
BR
Christian
