### ISSUE TITLE
Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#29]
Hi there, what's your recommendation on running horizontal pod autoscaler in the cluster? With the cashboxes being routed to the same pod and having a bit of overhead at the initialization time is hpa something you would recommend to run in the cluster ?

**Comment by fiskaltrust-ckr** [comment]
Hi, thanks for this question. We had pretty straight sizings until now. So we didn't use hpa. For me it is too far away to consider a recommendation but i will take this to our engineering and keep you updated...
BR Christian
