### ISSUE TITLE
Using BYOD with MSSQL-Server (Entity-Provider) Options

### ISSUE THREAD

**Issue by dietmarbaer** [fiskaltrust/product-de-bring-your-own-datacenter#30]
I want to use BYOD with MSSQL-Server. Because of size issues I want to have control over the database schema (using compression, creating indexes, using partitioning etc.) for data lifecycle management and long term storage.#
- How is the database schema created ? Will customized settings be rolled back by queue updates ?
- how is the lifecycle of the schema managed regarding schema changes on existing data ?
- What is the mapping between queues, database users, databases, schemas ?
I would prefer to use one SQL-Server database and one named schema per user, preferrably DBaaS like Azure SQL Database
Any helpful links are welcome

**Comment by fiskaltrust-ckr** [comment]
Hello,
unfortunately the EF/MSSQL provider is still under development. We should continue this discussion when this provider is released. Consider using MySQL for faster progress...
BR
