### ISSUE TITLE
Recommended database setup for production with SLA's

### ISSUE THREAD

**Issue by dietmarbaer** [fiskaltrust/product-de-bring-your-own-datacenter#35]
To get SLA's from our service provider for MySQL on VMWare we have to use a supported version of mysql or compatible database like:

- Oracle MySQL Enterprise
- Percona Server 
- Percona XtraDB Cluster
- MariaDB Platform
- ...
Any recommendations or certified platforms ?

**Comment by fiskaltrust-ckr** [comment]
Hi Dietmar,
thank you for asking.
Unfortunately, we have no recommendation for one of those platforms.
To our middleware in ByoDC it is important that your DB-Server is compatible with our client package: https://www.nuget.org/packages/MySqlConnector/1.2.0

BR
