### ISSUE TITLE
Retry handling with out of service response

### ISSUE THREAD

**Issue by mertcanyalhi** [fiskaltrust/product-de-bring-your-own-datacenter#37]
In cases where we receive out of service state (`0x4445000000000001`) for a signature request, we're trying to retry the request by first sending a receipt request (`ftReceiptCase` + "receipt request" flag - `0x0000800000000000`) to see if the receipt is generated or not, but we get the same response with the out of service state. In such cases, should we send the same signature request with the failed receipt flag (`ftReceiptCase` + "failed receipt" flag - `0x000000000000010000`)?

The documentation states that the TSE failure cases should not be retried, but there is no explicit information on the out of service state.

**Comment by TSchmiedlechner** [comment]
Hi @mertcanyalhi,
if I remember correctly, we've already clarified this issue via e-mail. 🙂 

Still answering here for future reference: If the Middleware is out of service, it means that it was either not initialized yet or already deactivated. In both cases, it will not be legally compliant to use this anyway; therefore, the MW needs to be initialized at the very beginning of the fiscalization process. 

It doesn't make much sense to retry this request, therefore, as the MW was not operated in the correct state at that time, and this scenario should anyway not occur in real-world scenarios.

**Comment by mertcanyalhi** [comment]
Hey @TSchmiedlechner yes, thank you! :)
