### ISSUE TITLE
BYOD: Error test with postman

### ISSUE THREAD

**Issue by SLSyntax** [fiskaltrust/product-de-bring-your-own-datacenter#43]
Hello,

our installation is like your  QuickStart guide.

All okay up to step 5 'Test reachability in the Browser' 

On Step 7 'Test with Postman' have we a probelm.

The first Postman step has a response 'IIS 8.5 Detailed Error - 404.0 - Not Found'.

The reason file a attached.
[Postman_response.html.txt](https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/files/6415102/Postman_response.html.txt)

**Comment by StefanKert** [comment]
Hi @SLSyntax,

this looks indeed a bit weird. Which port are you using for hosting? The error message that is returned is an IIS error message and we are using Ambassador for the balancing and Kestrel in the backend so there is no IIS used at the moment. Is it possible that you are using a port for another service that is located on your machine?

**Comment by SLSyntax** [comment]
Hallo Herr Kert,

wir setzen hier ein k8s auf Ubuntu ein .
Auch hier wir der Ambassador eingesetzt auf raten von Herrn Kreutzer.

**Comment by StefanKert** [comment]
@SLSyntax 

das ist auch absolut ok so. Im Rahmen des Helm Templates wird der Ambassador mit installiert. Die Frage war eher dahin gerichtet, ob es sein kann, das auf dem Rechner auf dem Sie testen noch ein IIS läuft der diesen Request abfängt, weil es technisch ausgeschlossen ist, dass wir eine IIS Fehlermeldung von unserem Backend zurückgeben.

**Comment by SLSyntax** [comment]
Hallo Herr Kert,

auf dem System läuft im k8s  z.Z. nur ein Namespace mit  ihrem  BYOD.

**Comment by SLSyntax** [comment]
Hallo,

die Fehlermeldung  'IIS 8.5 Detailed Error - 404.0 - Not Found'. kommt daher das der Postman den localhost als 'base_url '
benutzt.

Man sollte die Datei anpassen, bevor es in Postman geladen wird.
