### ISSUE TITLE
Status: 500 Internal Server Error 

### ISSUE THREAD

**Issue by SLSyntax** [fiskaltrust/product-de-bring-your-own-datacenter#46]
Hello,

we have this error after a new installation from byod today  

byod log attached

[byodc-789dcd5747-84tgt.log](https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/files/6494104/byodc-789dcd5747-84tgt.log)

**Comment by TSchmiedlechner** [comment]
Hi @SLSyntax,
could you please check which version of the images you are running? This looks like a bug that we have fixed with the latest release (1.3.19, released ~5 days ago) - could it be possible that you're still using a cached older image?

**Comment by SLSyntax** [comment]
Hi 

we have now the new version 'tag: 1.3-buster'  and now othe problems with mysql connect.

our connectionstring is 
Server=dawl036083.daw.fci.internal;Database=db_fiskaltrust_dev;Uid=dbu_fkt_dev;Pwd=XXXXXXXX

log attached
[byodc-74cf995948-smsw6.txt](https://github.com/fiskaltrust/product-de-bring-your-own-datacenter/files/6499252/byodc-74cf995948-smsw6.txt)

**Comment by SLSyntax** [comment]
Hi,

i have installed a mysql-client on this pod and the conncetion without problem's


root@byodc-74cf995948-smsw6:/app# mysql -h  dawl036083.daw.fci.internal  -u dbu_fkt_dev -par[e4Que@hie db_fiskaltrust_dev
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 78
Server version: 8.0.23 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [db_fiskaltrust_dev]> \q

mfg.
Sven Lange

**Comment by TSchmiedlechner** [comment]
Hi @SLSyntax, 
could the issue be that you specify the database in your connection string, or that the user's access is limited to this specific database? The Middleware creates it's own database (the name is generated from the Queue ID).

**Comment by SLSyntax** [comment]
Hallo @TSchmiedlechner ,

das ist  verwirrend wenn sie beim Anlegen eine Cashbox eine Datenbank angeben kann,.

Wir sind nun ein Stück weiter und bekommen die Fehlermeldung:

fail: fiskaltrust.SignatureCloud.DE.Services.MiddlewareInstanceFactory[0]
      Failed to create worker. casboxid: e67ee18d-31bc-41fd-85d2-3a22c5d78199
      System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'uriString'))
       ---> System.ArgumentNullException: Value cannot be null. (Parameter 'uriString')
         at System.Uri..ctor(String uriString)
         at fiskaltrust.Middleware.Localization.QueueDE.Services.DESSCDProvider.GetUriForSignaturCreationUnit(ftSignaturCreationUnitDE signaturCreationUnitDE)
         at fiskaltrust.Middleware.Localization.QueueDE.Services.DESSCDProvider.RegisterCurrentScuAsync()
         --- End of inner exception stack trace ---

**Comment by TSchmiedlechner** [comment]
Hallo @SLSyntax,
stimmt, wir werden das in der Doku eindeutiger klarstellen, die entstandenn Umstände tun uns leid.

Wir haben uns den Fall angesehen, und es sieht aus als hätten Sie in der SCU keine URL vergeben. Dies ist allerdings aus internen Gründen allerdings nötig. 

Uns ist auch aufgefallen, dass sich die aus der Queue referenzierte SCU nicht in der Cashbox befindet, sondern eine andere SCU hinzugefügt wurde; die aktuell verlinkte SCU `TEST_LOCAL_Boettcher` ist allerdings nicht konfiguriert, möglicherweise liegt das Problem daran.
