### ISSUE TITLE
Failed to execute ExportDataAsync

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#48]
**Describe the bug**

Hi there

We've see an increased number of timeouts this morning and we are trying to understand what caused it. The timeouts occured  at around 10 am UTC 15.06.2021. Below is the log from the byodc pod. Morning is usually the time when the daily receipts are triggered automatically on our system. 

`
{"id": "36210703916567195509667632233428298925726238547117735937", "timestamp": 1623744121293, "message": "{\"log\":\"\\u001B[41m\\u001B[30mfail\\u001B[39m\\u001B[22m\\u001B[49m: fiskaltrust.Middleware.SCU.DE.Fiskaly.FiskalySCU[0]\\n      Failed to execute ExportDataAsync - Request: {\\\"TokenId\\\":\\\"5b254fd3-34b7-40c9-b74f-3aa7aec80ebe\\\",\\\"MaxChunkSize\\\":1048576}\\n      Fiskaly.Errors.FiskalyHttpTimeoutError: HTTP timeout\\n         at Fiskaly.FiskalyHttpClient.ThrowOnError[T](JsonRpcResponse`1 response)\\n         at Fiskaly.FiskalyHttpClient.Request(String method, String path, Byte[] body, Dictionary`2 headers, Dictionary`2 query)\\n         at System.Threading.Tasks.Task`1.InnerInvoke()\\n         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\\n      --- End of stack trace from previous location ---\\n         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\\n      --- End of stack trace from previous location ---\\n         at fiskaltrust.Middleware.SCU.DE.Fiskaly.Helpers.FiskalyApiProvider.GetExportStateInformationByIdAsync(Guid tssId, Guid exportId)\\n         at fiskaltrust.Middleware.SCU.DE.Fiskaly.FiskalySCU.ExportDataAsync(ExportDataRequest request)\\n\",\"stream\":\"stdout\",\"docker\":{\"container_id\":\"f45f904bff42131df426b06e20351879fef22b3b7b72f0ea764467c037455625\"},\"kubernetes\":{\"container_name\":\"byodc\",\"namespace_name\":\"bring-your-own-datacenter\",\"pod_name\":\"byodc-7b4f76ff77-ntc45\",\"container_image\":\"ghcr.io/fiskaltrust/byodc-mysql-fiskaly:1.3.16-buster\",\"container_image_id\":\"docker-pullable://ghcr.io/fiskaltrust/byodc-mysql-fiskaly@sha256:e474c26458ea263e699871ee304a8f2c2d0b229cb0aa9d75333b0d300807489b\",\"pod_id\":\"f2ce4038-758d-4696-8bf2-565ce5398a5f\",\"host\":\"ip-192-168-157-187.eu-central-1.compute.internal\",\"labels\":{\"app\":\"byodc\",\"pod-template-hash\":\"7b4f76ff77\"},\"master_url\":\"https://10.100.0.1:443/api\",\"namespace_id\":\"55e764f3-dcc1-456b-a56a-02b4edd83cd7\"}}"}
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**STDOUT/STDERR**
If applicable, add LogOutput from affected BackendPOD.

**POSSystem (please complete the following information):**
- POSSystemID

**Cashbox Information (please complete the following information):**
 - CashboxID

**Additional context**

**Comment by TSchmiedlechner** [comment]
Hi @darek-phorest,
I think the underlying issue is the same as in #49, closing this now therefore. If you think it's a different topics, please let us know so that we can reopen this issue - thanks 🙂
