### ISSUE TITLE
Latest helm chart forces to change redis host name

### ISSUE THREAD

**Issue by darek-phorest** [fiskaltrust/product-de-bring-your-own-datacenter#53]
**Describe the bug**

latest chart version 1.3.18 breaks our redis url and doesn't allow to override the full redis host

version: 1.3.18 in templates/manifest/byodc.yml
```
  env:
            - name: Redis__ConnectionString
              value: {{ .Values.byodc.config.redis.host }}.{{ .Release.Namespace }}:{{ .Values.byodc.config.redis.port }}
```

vs 1.3.16
```
 - name: Redis__ConnectionString
              value: {{ .Values.byodc.config.redis.host }}:{{ .Values.byodc.config.redis.port }}
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**STDOUT/STDERR**
If applicable, add LogOutput from affected BackendPOD.

**POSSystem (please complete the following information):**
- POSSystemID

**Cashbox Information (please complete the following information):**
 - CashboxID

**Additional context**

**Comment by volllly** [comment]
Hello @darek-phorest,

Sorry for the inconvenience. We will provide a fix for this issue in the next version (which will probably be released later this week).

**Comment by TSchmiedlechner** [comment]
Hi @darek-phorest,
we've released version 1.3.22 of BYODC which fixes this issue in our tests. Please note that it's also required to update the Chart (not just the container).

Enjoy your weekend!
Tom

**Comment by darek-phorest** [comment]
hi @TSchmiedlechner 

thanks for the update, i assume the new chart version is not released yet: https://charts.fiskaltrust.cloud/ as 1.3.18 is still the latest.

**Comment by TSchmiedlechner** [comment]
Good morning,
sorry, looks like the deployment was waiting in the approval stage. The latest chart version has now been deployed.
