### ISSUE TITLE
Meaning of "middleware not created" after quickstart guide

### ISSUE THREAD

**Issue by dhuesmann89** [fiskaltrust/product-de-bring-your-own-datacenter#54]
I followed the quickstart guide, the k8s components are up and running and I can reach them from outside.
I can also communicate with my MySQL database (hosted in Azure) from my workstation using the connection string set up in the Fiskaltrust queue.
But when I run the Echo example from the Postman collection I get the message "middleware not created".
Where could I have missed something?

**Comment by dhuesmann89** [comment]
Seems like I missed a step. After redoing the quickstart guide it works xD

**Comment by TSchmiedlechner** [comment]
Great to hear, thanks for the update! 😄
