### ISSUE TITLE
Error: INSTALLATION FAILED: failed to install CRD crds/filter.yaml

### ISSUE THREAD

**Issue by SLSyntax** [fiskaltrust/product-de-bring-your-own-datacenter#56]
**Describe the bug**
Error by installation  of bring-your-own-datacenter

# helm install bring-your-own-datacenter fiskaltrust/bring-your-own-datacenter
Error: INSTALLATION FAILED: failed to install CRD crds/filter.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"

**To Reproduce**
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

# helm version  
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}

# helm repo list
NAME       	URL                              
fiskaltrust	https://charts.fiskaltrust.cloud/

# helm search repo fiskaltrust
NAME                                 	CHART VERSION	APP VERSION	DESCRIPTION
fiskaltrust/bring-your-own-datacenter	1.3.23

**Comment by volllly** [comment]
Hi,

we've just released `v1.3.26` of the helm chart which is upgraded to the newer ambassador 2.0 stack which fixes this problem.

Please follow the [Migration Guide](https://github.com/fiskaltrust/helm-charts/blob/master/bring-your-own-datacenter/MIGRATION.md#v1326) for this update. Not doing so will break your byodc installation. Byodc will be down during the update.
