### ISSUE TITLE
Can you provide a list of all the APIs exposed by fiskaltrust.Middleware?

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/product-de-bring-your-own-datacenter#6]
Can you provide a list of all the APIs exposed by fiskaltrust.Middleware?

**Comment by fiskaltrust-ckr** [comment]
We will add Swagger Endpoints with the upcoming Release (coming probably next week).

Till then we are exposing the following APIs:
/api/echo
/api/v1/echo
/json/echo
/json/v1/echo
/xml/echo
/xml/v1/echo
/api/sign
/api/v1/sign
/json/sign
/json/v1/sign
/xml/sign
/xml/v1/sign
/api/journal
/api/v1/journal
/json/journal
/json/v1/journal
/xml/journal
/xml/v1/journal
/api/v0/version
/json/v0/version
/xml/v0/version
