### ISSUE TITLE
Queue DB Index Creation manual procedure

### ISSUE THREAD

**Issue by fiskaltrust-ckr** [fiskaltrust/product-de-bring-your-own-datacenter#69]
Get a DB Procedure or script where Index creation (MW 1.3.37 change) can be run manually

**Comment by volllly** [comment]
Hey 😁, you can find that in the MW MySQL migrations https://github.com/fiskaltrust/middleware/blob/main/queue/src/fiskaltrust.Middleware.Storage.MySQL/Migrations/005_Indices.mysql

```sql
ALTER TABLE ftQueueItem MODIFY cbReceiptReference VARCHAR(450);
CREATE INDEX idx_ftQueueItem_Timestamp ON ftQueueItem (TimeStamp);
CREATE INDEX idx_ftQueueItem_cbReceiptReference ON ftQueueItem (cbReceiptReference);
CREATE INDEX idx_ftActionJournal_Timestamp ON ftActionJournal (TimeStamp);
CREATE INDEX idx_ftReceiptJournal_Timestamp ON ftReceiptJournal (TimeStamp);
CREATE INDEX idx_ftJournalAT_Timestamp ON ftJournalAT (TimeStamp);
CREATE INDEX idx_ftJournalDE_Timestamp ON ftJournalDE (TimeStamp);
CREATE INDEX idx_ftJournalFR_Timestamp ON ftJournalFR (TimeStamp);
```

**Comment by volllly** [comment]
No that is not (easily) possible as mysql does not support the `if not exists` syntax 🥲 

but when you include this in the script `SET SQL_SAFE_UPDATES = 0;UPDATE ftDatabaseSchema SET CurrentVersion = "005_Indices;SET SQL_SAFE_UPDATES = 1;` the migrator will not attempt the index creation on queue startup again. (I have not tried this yet. also you should probably check beforehand if the 004 migrations are alerady performed or they will be skipped after setting the version to 005)

> Do we have any insights on the time it takes to execute the first statement?

nothing concrete. less than a second on small dbs more than 30 on larger ones.

**Comment by volllly** [comment]
[Here](https://gist.github.com/volllly/3574d5b06a8736fd03eb769e4ecb4e6c) you can find the script to verify the indexes were created successfully.

The result of this script should be a row with the following data:

| ftQueueItem_cbReceiptReference_dataType | idx_ftQueueItem_Timestamp | idx_ftQueueItem_cbReceiptReference | idx_ftActionJournal_Timestamp | idx_ftReceiptJournal_Timestamp | idx_ftJournalAT_Timestamp | idx_ftJournalDE_Timestamp | idx_ftJournalFR_Timestamp | ftDatabase_schema_version |
|-----------------------------------------|---------------------------|------------------------------------|-------------------------------|--------------------------------|---------------------------|---------------------------|---------------------------|---------------------------|
| 1                                       | 1                         | 1                                  | 1                             | 1                              | 1                         | 1                         | 1                         | 1                         |

If theres a `0` in any of the columns this means something went wrong.
