### ISSUE TITLE
Do you have any dimensioning guidelines for the fiskaltrust.Middleware database (storage, CPU)

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/product-de-bring-your-own-datacenter#7]
Do you have any dimensioning guidelines for the fiskaltrust.Middleware database (storage, CPU)

**Comment by fiskaltrust-ckr** [comment]
This is a new product, we did some theoretical sizing:

Cashboxes per Backend POD -> 500
Single Receipt Size (KB) -> 10
Backend POD Storage amount (GB) -> 10
Backend POD RAM amount (GB) -> 16
Backend POD vCPU amount -> 4
Backend POD spare count -> 1

But this depends on how your environment looks like. You may operate with performance and SLA of your own needs.
