### ISSUE TITLE
Receipt signing fails with: "configuration not readable"

### ISSUE THREAD

**Issue by JakubBereznicki62** [fiskaltrust/product-de-bring-your-own-datacenter#79]
**Describe the bug**
We recently started to see many responses with 400 status code and "configuration not readable" message when signing receipts. We were able to sign some of the receipts after several tries.

**To Reproduce**
Example request:
```
{
   "ftReceiptCase":4919478909755523073,
   "ftCashBoxID":"9a142587-22a9-4f9c-8aa4-bfdb01955e8c",
   "cbTerminalID":"dVgfaVmeQ6emPOm28mMYqw",
   "cbReceiptReference":"A109",
   "cbReceiptMoment":"2024-01-12T17:32:03.000Z",
   "cbChargeItems":[
      {
         "ftChargeItemCase":4919338167972135059,
         "Quantity":1,
         "Description":"Bankeinzahlung",
         "Amount":-400.00,
         "VATRate":0
      }
   ],
   "cbPayItems":[
      {
         "ftPayItemCase":4919338167972134913,
         "Quantity":1,
         "Description":"Bar",
         "Amount":-400.00
      }
   ],
   "ftPosSystemId":"b2460c21-f12b-4b2c-9bf4-a9487f8ede57"
}
```

**Expected behavior**
Requests are processed correctly

POSSystem (please complete the following information):
b2460c21-f12b-4b2c-9bf4-a9487f8ede57

**Cashbox Information (please complete the following information):**
Some example cashbox ids:
- a7218809-9c87-46c8-b67b-2c5ec45a51a0
- 429900d3-c2a4-4752-bf4d-605fb3b612ea
- 9a142587-22a9-4f9c-8aa4-bfdb01955e8c

**Comment by volllly** [comment]
Hey, we we're not able to consistently reproduce this so it's hard to tell if we fixed it but we've made the configuration download more robust and improved logging around it in the new `1.3.55-rc1` version.

Could you check if this problem still occurs in this version and if it does share some logs from when its happening with us 🙏

**Comment by mertcanyalhi** [comment]
@volllly the issue can be reproduced with the following steps:

1. Start a ByoDC instance
2. Send a signature request - ByoDC will load the cashbox configuration
3. Wait for 61 minutes, and send another signature request - observe 400 response with "configuration not readable" response body

We'll test 1.3.55-rc1, and will let you know.

**Comment by JakubBereznicki62** [comment]
Hey @volllly we updated to 1.3.55-rc1 and it seems that it fixed the issue 👍
