### ISSUE TITLE
Do you have any dimensioning guidelines for the Redis cache (assuming Amazon ElastiCache)

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/product-de-bring-your-own-datacenter#8]
Do you have any dimensioning guidelines for the Redis cache (assuming Amazon ElastiCache)

**Comment by fiskaltrust-ckr** [comment]
This depends strongly on the usage profile. In this case, redis is used to sync the backendpods and to ensure that all cashboxes are running as singletons. I suggest to start with a small instance and take a look how databasesize and serverload is developing during your tests. If you use it as PaaS there should be a scaling option to fit your needs.
