### ISSUE TITLE
Database Connection Properties Configuration

### ISSUE THREAD

**Issue by Solrosy** [fiskaltrust/product-de-bring-your-own-datacenter#9]
From the ByoDC documentation, it appears that the database connection properties are configured via the fiskal portal. Is there a way to automate this, for example using configuration files or scripting via an API?

**Comment by fiskaltrust-ckr** [comment]
Indeed, we have several tools to automate the client rollout. Please look at our docs:
https://docs.fiskaltrust.cloud/doc/productdescription-de-doc/for-posdealers/02-pre-sales/automatisierter-rollout.html
